//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssetUpdate")]
  public partial class AssetUpdate : global::ProtoBuf.IExtensible
  {
    public AssetUpdate() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private int _nGold = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nGold
    {
      get { return _nGold; }
      set { _nGold = value; }
    }
    private int _nMoney = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nMoney
    {
      get { return _nMoney; }
      set { _nMoney = value; }
    }
    private string _sAssets = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sAssets
    {
      get { return _sAssets; }
      set { _sAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}