//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: auth.proto
// Note: requires additional types generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VCodeRequest")]
  public partial class VCodeRequest : global::ProtoBuf.IExtensible
  {
    public VCodeRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sPhone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sPhone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sPhone
    {
      get { return _sPhone; }
      set { _sPhone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VCodeResponse")]
  public partial class VCodeResponse : global::ProtoBuf.IExtensible
  {
    public VCodeResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private string _sVCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sVCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sVCode
    {
      get { return _sVCode; }
      set { _sVCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthRequest")]
  public partial class AuthRequest : global::ProtoBuf.IExtensible
  {
    public AuthRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sPhone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sPhone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sPhone
    {
      get { return _sPhone; }
      set { _sPhone = value; }
    }
    private string _sVCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sVCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sVCode
    {
      get { return _sVCode; }
      set { _sVCode = value; }
    }
    private string _sRealName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sRealName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRealName
    {
      get { return _sRealName; }
      set { _sRealName = value; }
    }
    private string _sSFZ;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sSFZ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sSFZ
    {
      get { return _sSFZ; }
      set { _sSFZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthResponse")]
  public partial class AuthResponse : global::ProtoBuf.IExtensible
  {
    public AuthResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newasset = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newasset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AssetUpdate newasset
    {
      get { return _newasset; }
      set { _newasset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}