//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: baopai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaoPaiShowNotify")]
  public partial class BaoPaiShowNotify : global::ProtoBuf.IExtensible
  {
    public BaoPaiShowNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private ProtoMsg.Pai _baopai;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"baopai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai baopai
    {
      get { return _baopai; }
      set { _baopai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaoPaiChangeNotify")]
  public partial class BaoPaiChangeNotify : global::ProtoBuf.IExtensible
  {
    public BaoPaiChangeNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private ProtoMsg.Pai _newBao;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newBao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai newBao
    {
      get { return _newBao; }
      set { _newBao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}