//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: broadcast.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadCast")]
  public partial class BroadCast : global::ProtoBuf.IExtensible
  {
    public BroadCast() {}
    
    private int _nID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nID
    {
      get { return _nID; }
      set { _nID = value; }
    }
    private string _sTitle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sTitle
    {
      get { return _sTitle; }
      set { _sTitle = value; }
    }
    private string _sDetail;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sDetail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sDetail
    {
      get { return _sDetail; }
      set { _sDetail = value; }
    }
    private string _sDate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sDate
    {
      get { return _sDate; }
      set { _sDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadCastRequest")]
  public partial class BroadCastRequest : global::ProtoBuf.IExtensible
  {
    public BroadCastRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadCastResponse")]
  public partial class BroadCastResponse : global::ProtoBuf.IExtensible
  {
    public BroadCastResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.BroadCast> _bPool = new global::System.Collections.Generic.List<ProtoMsg.BroadCast>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.BroadCast> bPool
    {
      get { return _bPool; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}