//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: buy.proto
// Note: requires additional types generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Good")]
  public partial class Good : global::ProtoBuf.IExtensible
  {
    public Good() {}
    
    private int _nID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nID
    {
      get { return _nID; }
      set { _nID = value; }
    }
    private int _nCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nCount
    {
      get { return _nCount; }
      set { _nCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyRequest")]
  public partial class BuyRequest : global::ProtoBuf.IExtensible
  {
    public BuyRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.Good> _goods = new global::System.Collections.Generic.List<ProtoMsg.Good>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.Good> goods
    {
      get { return _goods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyResponse")]
  public partial class BuyResponse : global::ProtoBuf.IExtensible
  {
    public BuyResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppleBuyRequest")]
  public partial class AppleBuyRequest : global::ProtoBuf.IExtensible
  {
    public AppleBuyRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.Good> _goods = new global::System.Collections.Generic.List<ProtoMsg.Good>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.Good> goods
    {
      get { return _goods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppleBuyResponse")]
  public partial class AppleBuyResponse : global::ProtoBuf.IExtensible
  {
    public AppleBuyResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}