//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: can_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanPaiNotify")]
  public partial class CanPaiNotify : global::ProtoBuf.IExtensible
  {
    public CanPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private ProtoMsg.Pai _lastPai = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai lastPai
    {
      get { return _lastPai; }
      set { _lastPai = value; }
    }
    private bool _canTing = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"canTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canTing
    {
      get { return _canTing; }
      set { _canTing = value; }
    }
    private bool _canHu = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"canHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canHu
    {
      get { return _canHu; }
      set { _canHu = value; }
    }
    private bool _canQiangTing = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"canQiangTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canQiangTing
    {
      get { return _canQiangTing; }
      set { _canQiangTing = value; }
    }
    private bool _canGang = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"canGang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canGang
    {
      get { return _canGang; }
      set { _canGang = value; }
    }
    private bool _canPeng = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"canPeng", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canPeng
    {
      get { return _canPeng; }
      set { _canPeng = value; }
    }
    private bool _canChi = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"canChi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canChi
    {
      get { return _canChi; }
      set { _canChi = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.ChiPai> _canChiPool = new global::System.Collections.Generic.List<ProtoMsg.ChiPai>();
    [global::ProtoBuf.ProtoMember(9, Name=@"canChiPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.ChiPai> canChiPool
    {
      get { return _canChiPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.Pai> _canPengPool = new global::System.Collections.Generic.List<ProtoMsg.Pai>();
    [global::ProtoBuf.ProtoMember(10, Name=@"canPengPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.Pai> canPengPool
    {
      get { return _canPengPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.GangPai> _canGangPool = new global::System.Collections.Generic.List<ProtoMsg.GangPai>();
    [global::ProtoBuf.ProtoMember(11, Name=@"canGangPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.GangPai> canGangPool
    {
      get { return _canGangPool; }
    }
  
    private int _lastHuType = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"lastHuType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastHuType
    {
      get { return _lastHuType; }
      set { _lastHuType = value; }
    }
    private bool _bZm = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bZm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bZm
    {
      get { return _bZm; }
      set { _bZm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}