//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: create_room.proto
// Note: requires additional types generated from: gameplay.proto
// Note: requires additional types generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomRequest")]
  public partial class CreateRoomRequest : global::ProtoBuf.IExtensible
  {
    public CreateRoomRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sCardType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sCardType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sCardType
    {
      get { return _sCardType; }
      set { _sCardType = value; }
    }
    private ProtoMsg.GamePlay _gamePlay;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gamePlay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.GamePlay gamePlay
    {
      get { return _gamePlay; }
      set { _gamePlay = value; }
    }
    private int _nPlayers;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nPlayers
    {
      get { return _nPlayers; }
      set { _nPlayers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomResponse")]
  public partial class CreateRoomResponse : global::ProtoBuf.IExtensible
  {
    public CreateRoomResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private string _sRoomID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private string _sCardType = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sCardType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sCardType
    {
      get { return _sCardType; }
      set { _sCardType = value; }
    }
    private ProtoMsg.GamePlay _gamePlay = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gamePlay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GamePlay gamePlay
    {
      get { return _gamePlay; }
      set { _gamePlay = value; }
    }
    private int _nPlayers = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nPlayers
    {
      get { return _nPlayers; }
      set { _nPlayers = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}