//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: do_chi_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoChiPaiRequest")]
  public partial class DoChiPaiRequest : global::ProtoBuf.IExtensible
  {
    public DoChiPaiRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _pai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private int _nChiIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nChiIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nChiIndex
    {
      get { return _nChiIndex; }
      set { _nChiIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoChiPaiResponse")]
  public partial class DoChiPaiResponse : global::ProtoBuf.IExtensible
  {
    public DoChiPaiResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private int _nLastID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nLastID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nLastID
    {
      get { return _nLastID; }
      set { _nLastID = value; }
    }
    private ProtoMsg.Pai _lastPai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai lastPai
    {
      get { return _lastPai; }
      set { _lastPai = value; }
    }
    private int _nChiIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nChiIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nChiIndex
    {
      get { return _nChiIndex; }
      set { _nChiIndex = value; }
    }
    private ProtoMsg.ChiPai _pai;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.ChiPai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoChiPaiNotify")]
  public partial class DoChiPaiNotify : global::ProtoBuf.IExtensible
  {
    public DoChiPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.ChiPai _pai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.ChiPai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private int _nLastID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nLastID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nLastID
    {
      get { return _nLastID; }
      set { _nLastID = value; }
    }
    private ProtoMsg.Pai _lastPai;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lastPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai lastPai
    {
      get { return _lastPai; }
      set { _lastPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}