//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: do_peng_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoPengPaiRequest")]
  public partial class DoPengPaiRequest : global::ProtoBuf.IExtensible
  {
    public DoPengPaiRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _pai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoPengPaiResponse")]
  public partial class DoPengPaiResponse : global::ProtoBuf.IExtensible
  {
    public DoPengPaiResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private int _nLastID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nLastID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nLastID
    {
      get { return _nLastID; }
      set { _nLastID = value; }
    }
    private ProtoMsg.Pai _lastPai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai lastPai
    {
      get { return _lastPai; }
      set { _lastPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoPengPaiNotify")]
  public partial class DoPengPaiNotify : global::ProtoBuf.IExtensible
  {
    public DoPengPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _pai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private int _nLastID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nLastID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nLastID
    {
      get { return _nLastID; }
      set { _nLastID = value; }
    }
    private ProtoMsg.Pai _lastPai;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lastPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai lastPai
    {
      get { return _lastPai; }
      set { _lastPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}