//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: do_ting_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoTingPaiRequest")]
  public partial class DoTingPaiRequest : global::ProtoBuf.IExtensible
  {
    public DoTingPaiRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _pai = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoTingPaiResponse")]
  public partial class DoTingPaiResponse : global::ProtoBuf.IExtensible
  {
    public DoTingPaiResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoTingPaiNotify")]
  public partial class DoTingPaiNotify : global::ProtoBuf.IExtensible
  {
    public DoTingPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _pai = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}