//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: exchange.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExchangeRequest")]
  public partial class ExchangeRequest : global::ProtoBuf.IExtensible
  {
    public ExchangeRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private ProtoMsg.EnumExchange _nType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoMsg.EnumExchange nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nCount
    {
      get { return _nCount; }
      set { _nCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExchangeResponse")]
  public partial class ExchangeResponse : global::ProtoBuf.IExtensible
  {
    public ExchangeResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.EnumExchange _nType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoMsg.EnumExchange nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nCountL = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nCountL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nCountL
    {
      get { return _nCountL; }
      set { _nCountL = value; }
    }
    private int _nCountR = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nCountR", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nCountR
    {
      get { return _nCountR; }
      set { _nCountR = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnumExchange")]
    public enum EnumExchange
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRYSTAL2GOLD", Value=0)]
      CRYSTAL2GOLD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD2POWER", Value=1)]
      GOLD2POWER = 1
    }
  
}