//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_end.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GamerInfo")]
  public partial class GamerInfo : global::ProtoBuf.IExtensible
  {
    public GamerInfo() {}
    
    private ProtoMsg.GamerPaiPool _gamerPai;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gamerPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.GamerPaiPool gamerPai
    {
      get { return _gamerPai; }
      set { _gamerPai = value; }
    }
    private int _nGameCoin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nGameCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nGameCoin
    {
      get { return _nGameCoin; }
      set { _nGameCoin = value; }
    }
    private bool _bHu;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bHu
    {
      get { return _bHu; }
      set { _bHu = value; }
    }
    private bool _bTing;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bTing
    {
      get { return _bTing; }
      set { _bTing = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _nHuOPList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"nHuOPList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> nHuOPList
    {
      get { return _nHuOPList; }
    }
  
    private int _nID = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nID
    {
      get { return _nID; }
      set { _nID = value; }
    }
    private bool _bBoss = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bBoss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bBoss
    {
      get { return _bBoss; }
      set { _bBoss = value; }
    }
    private ProtoMsg.Pai _hupai = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hupai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai hupai
    {
      get { return _hupai; }
      set { _hupai = value; }
    }
    private int _huCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"huCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int huCount
    {
      get { return _huCount; }
      set { _huCount = value; }
    }
    private int _moBaoCount = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"moBaoCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moBaoCount
    {
      get { return _moBaoCount; }
      set { _moBaoCount = value; }
    }
    private int _ziMoCount = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ziMoCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ziMoCount
    {
      get { return _ziMoCount; }
      set { _ziMoCount = value; }
    }
    private int _gangCount = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"gangCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangCount
    {
      get { return _gangCount; }
      set { _gangCount = value; }
    }
    private int _dianPaoCount = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"dianPaoCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dianPaoCount
    {
      get { return _dianPaoCount; }
      set { _dianPaoCount = value; }
    }
    private int _danJuBestCount = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"danJuBestCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int danJuBestCount
    {
      get { return _danJuBestCount; }
      set { _danJuBestCount = value; }
    }
    private int _totalScore = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEndNotify")]
  public partial class GameEndNotify : global::ProtoBuf.IExtensible
  {
    public GameEndNotify() {}
    
    private ProtoMsg.Pai _bao = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai bao
    {
      get { return _bao; }
      set { _bao = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.GamerInfo> _infoList = new global::System.Collections.Generic.List<ProtoMsg.GamerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"infoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.GamerInfo> infoList
    {
      get { return _infoList; }
    }
  
    private bool _bHuang = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bHuang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bHuang
    {
      get { return _bHuang; }
      set { _bHuang = value; }
    }
    private bool _bOver = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bOver
    {
      get { return _bOver; }
      set { _bOver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}