//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gamer.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Gamer")]
  public partial class Gamer : global::ProtoBuf.IExtensible
  {
    public Gamer() {}
    
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private int _nGID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nGID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nGID
    {
      get { return _nGID; }
      set { _nGID = value; }
    }
    private int _nPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nPos
    {
      get { return _nPos; }
      set { _nPos = value; }
    }
    private bool _bBoss;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bBoss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bBoss
    {
      get { return _bBoss; }
      set { _bBoss = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private bool _bOwner;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"bOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bOwner
    {
      get { return _bOwner; }
      set { _bOwner = value; }
    }
    private string _sName;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sName
    {
      get { return _sName; }
      set { _sName = value; }
    }
    private string _sHeadImage;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"sHeadImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sHeadImage
    {
      get { return _sHeadImage; }
      set { _sHeadImage = value; }
    }
    private ProtoMsg.GamerPaiPool _paipool = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"paipool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GamerPaiPool paipool
    {
      get { return _paipool; }
      set { _paipool = value; }
    }
    private bool _bOnline = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bOnline
    {
      get { return _bOnline; }
      set { _bOnline = value; }
    }
    private int _totalScore = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
    private int _gameState = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"gameState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameState
    {
      get { return _gameState; }
      set { _gameState = value; }
    }
    private bool _bAI = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bAI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bAI
    {
      get { return _bAI; }
      set { _bAI = value; }
    }
    private int _nGender = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"nGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nGender
    {
      get { return _nGender; }
      set { _nGender = value; }
    }
    private int _nAIRandInfo = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"nAIRandInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nAIRandInfo
    {
      get { return _nAIRandInfo; }
      set { _nAIRandInfo = value; }
    }
    private int _nAIRandHead = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"nAIRandHead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nAIRandHead
    {
      get { return _nAIRandHead; }
      set { _nAIRandHead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}