//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gameplay.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GamePlay")]
  public partial class GamePlay : global::ProtoBuf.IExtensible
  {
    public GamePlay() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _optionals = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"optionals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> optionals
    {
      get { return _optionals; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}