//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guo_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuoPaiRequest")]
  public partial class GuoPaiRequest : global::ProtoBuf.IExtensible
  {
    public GuoPaiRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private int _nType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuoPaiResponse")]
  public partial class GuoPaiResponse : global::ProtoBuf.IExtensible
  {
    public GuoPaiResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuoPaiNotify")]
  public partial class GuoPaiNotify : global::ProtoBuf.IExtensible
  {
    public GuoPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}