//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: join_room.proto
// Note: requires additional types generated from: gamer.proto
// Note: requires additional types generated from: gameplay.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room")]
  public partial class Room : global::ProtoBuf.IExtensible
  {
    public Room() {}
    
    private string _sID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sID
    {
      get { return _sID; }
      set { _sID = value; }
    }
    private ProtoMsg.GamePlay _gamePlay;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gamePlay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.GamePlay gamePlay
    {
      get { return _gamePlay; }
      set { _gamePlay = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.Gamer> _Gamers = new global::System.Collections.Generic.List<ProtoMsg.Gamer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Gamers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.Gamer> Gamers
    {
      get { return _Gamers; }
    }
  
    private int _nState = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nState
    {
      get { return _nState; }
      set { _nState = value; }
    }
    private int _nCardCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nCardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nCardCount
    {
      get { return _nCardCount; }
      set { _nCardCount = value; }
    }
    private int _nPlayers = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nPlayers
    {
      get { return _nPlayers; }
      set { _nPlayers = value; }
    }
    private string _sCardType = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sCardType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sCardType
    {
      get { return _sCardType; }
      set { _sCardType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomRequest")]
  public partial class JoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public JoinRoomRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomResponse")]
  public partial class JoinRoomResponse : global::ProtoBuf.IExtensible
  {
    public JoinRoomResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.Room _joinRoom = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"joinRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Room joinRoom
    {
      get { return _joinRoom; }
      set { _joinRoom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomNotify")]
  public partial class JoinRoomNotify : global::ProtoBuf.IExtensible
  {
    public JoinRoomNotify() {}
    
    private ProtoMsg.Gamer _joinGamer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"joinGamer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Gamer joinGamer
    {
      get { return _joinGamer; }
      set { _joinGamer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}