//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User")]
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sNick = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sNick
    {
      get { return _sNick; }
      set { _sNick = value; }
    }
    private int _nExp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nExp
    {
      get { return _nExp; }
      set { _nExp = value; }
    }
    private int _nGold = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nGold
    {
      get { return _nGold; }
      set { _nGold = value; }
    }
    private int _nMoney = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nMoney
    {
      get { return _nMoney; }
      set { _nMoney = value; }
    }
    private string _sHeadimg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sHeadimg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sHeadimg
    {
      get { return _sHeadimg; }
      set { _sHeadimg = value; }
    }
    private string _sPhone = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sPhone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sPhone
    {
      get { return _sPhone; }
      set { _sPhone = value; }
    }
    private string _sRecords = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sRecords
    {
      get { return _sRecords; }
      set { _sRecords = value; }
    }
    private string _sAssets = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sAssets
    {
      get { return _sAssets; }
      set { _sAssets = value; }
    }
    private string _sRoom = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sRoom
    {
      get { return _sRoom; }
      set { _sRoom = value; }
    }
    private int _nParent = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nParent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nParent
    {
      get { return _nParent; }
      set { _nParent = value; }
    }
    private string _sICode = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sICode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sICode
    {
      get { return _sICode; }
      set { _sICode = value; }
    }
    private string _sName = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"sName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sName
    {
      get { return _sName; }
      set { _sName = value; }
    }
    private bool _bLuckyToday = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"bLuckyToday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bLuckyToday
    {
      get { return _bLuckyToday; }
      set { _bLuckyToday = value; }
    }
    private bool _bWelfareToday = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"bWelfareToday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bWelfareToday
    {
      get { return _bWelfareToday; }
      set { _bWelfareToday = value; }
    }
    private int _nGender = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"nGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nGender
    {
      get { return _nGender; }
      set { _nGender = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _bRkAwardFlags = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(17, Name=@"bRkAwardFlags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> bRkAwardFlags
    {
      get { return _bRkAwardFlags; }
    }
  
    private bool _bShareAwardWeek = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"bShareAwardWeek", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bShareAwardWeek
    {
      get { return _bShareAwardWeek; }
      set { _bShareAwardWeek = value; }
    }
    private int _nWinCount = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"nWinCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nWinCount
    {
      get { return _nWinCount; }
      set { _nWinCount = value; }
    }
    private int _nTotalCount = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"nTotalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nTotalCount
    {
      get { return _nTotalCount; }
      set { _nTotalCount = value; }
    }
    private string _sIP = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"sIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sIP
    {
      get { return _sIP; }
      set { _sIP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _sName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sName
    {
      get { return _sName; }
      set { _sName = value; }
    }
    private string _sPassWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sPassWord
    {
      get { return _sPassWord; }
      set { _sPassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginWXRequest")]
  public partial class LoginWXRequest : global::ProtoBuf.IExtensible
  {
    public LoginWXRequest() {}
    
    private string _sOpenID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sOpenID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sOpenID
    {
      get { return _sOpenID; }
      set { _sOpenID = value; }
    }
    private string _sNick = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sNick
    {
      get { return _sNick; }
      set { _sNick = value; }
    }
    private string _sHeadImage = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sHeadImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sHeadImage
    {
      get { return _sHeadImage; }
      set { _sHeadImage = value; }
    }
    private int _nGender = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nGender
    {
      get { return _nGender; }
      set { _nGender = value; }
    }
    private string _iCode = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string iCode
    {
      get { return _iCode; }
      set { _iCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.User _requester = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requester", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.User requester
    {
      get { return _requester; }
      set { _requester = value; }
    }
    private int _rookieAward = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rookieAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rookieAward
    {
      get { return _rookieAward; }
      set { _rookieAward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginOutRequest")]
  public partial class LoginOutRequest : global::ProtoBuf.IExtensible
  {
    public LoginOutRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginOutResponse")]
  public partial class LoginOutResponse : global::ProtoBuf.IExtensible
  {
    public LoginOutResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}