//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail")]
  public partial class Mail : global::ProtoBuf.IExtensible
  {
    public Mail() {}
    
    private int _nID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nID
    {
      get { return _nID; }
      set { _nID = value; }
    }
    private int _nUID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nUID
    {
      get { return _nUID; }
      set { _nUID = value; }
    }
    private int _nType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private string _sContent = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sContent
    {
      get { return _sContent; }
      set { _sContent = value; }
    }
    private string _sTime = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sTime
    {
      get { return _sTime; }
      set { _sTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailRequest")]
  public partial class MailRequest : global::ProtoBuf.IExtensible
  {
    public MailRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailResponse")]
  public partial class MailResponse : global::ProtoBuf.IExtensible
  {
    public MailResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.Mail> _mails = new global::System.Collections.Generic.List<ProtoMsg.Mail>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.Mail> mails
    {
      get { return _mails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}