//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
// Note: requires additional types generated from: can_pai.proto
// Note: requires additional types generated from: create_room.proto
// Note: requires additional types generated from: do_chi_pai.proto
// Note: requires additional types generated from: do_gang_pai.proto
// Note: requires additional types generated from: do_hu_pai.proto
// Note: requires additional types generated from: do_peng_pai.proto
// Note: requires additional types generated from: do_ting_pai.proto
// Note: requires additional types generated from: game_end.proto
// Note: requires additional types generated from: get_pai.proto
// Note: requires additional types generated from: put_pai.proto
// Note: requires additional types generated from: join_room.proto
// Note: requires additional types generated from: leave_room.proto
// Note: requires additional types generated from: login.proto
// Note: requires additional types generated from: register.proto
// Note: requires additional types generated from: start_game.proto
// Note: requires additional types generated from: guo_pai.proto
// Note: requires additional types generated from: buy.proto
// Note: requires additional types generated from: broadcast.proto
// Note: requires additional types generated from: baopai.proto
// Note: requires additional types generated from: rookie.proto
// Note: requires additional types generated from: game_time.proto
// Note: requires additional types generated from: auth.proto
// Note: requires additional types generated from: suggest.proto
// Note: requires additional types generated from: login_heart.proto
// Note: requires additional types generated from: do_qiang_ting_pai.proto
// Note: requires additional types generated from: diss_room.proto
// Note: requires additional types generated from: netconnect.proto
// Note: requires additional types generated from: chat.proto
// Note: requires additional types generated from: log.proto
// Note: requires additional types generated from: lucky.proto
// Note: requires additional types generated from: assets.proto
// Note: requires additional types generated from: welfare.proto
// Note: requires additional types generated from: rank.proto
// Note: requires additional types generated from: delegate.proto
// Note: requires additional types generated from: share.proto
// Note: requires additional types generated from: mail.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private ProtoMsg.RegisterRequest _registerRequest = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"registerRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RegisterRequest registerRequest
    {
      get { return _registerRequest; }
      set { _registerRequest = value; }
    }
    private ProtoMsg.LoginRequest _loginRquest = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginRquest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginRequest loginRquest
    {
      get { return _loginRquest; }
      set { _loginRquest = value; }
    }
    private ProtoMsg.CreateRoomRequest _createRoomRequest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createRoomRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.CreateRoomRequest createRoomRequest
    {
      get { return _createRoomRequest; }
      set { _createRoomRequest = value; }
    }
    private ProtoMsg.JoinRoomRequest _joinRoomRequest = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"joinRoomRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.JoinRoomRequest joinRoomRequest
    {
      get { return _joinRoomRequest; }
      set { _joinRoomRequest = value; }
    }
    private ProtoMsg.LeaveRoomRequest _leaveRoomRequest = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"leaveRoomRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LeaveRoomRequest leaveRoomRequest
    {
      get { return _leaveRoomRequest; }
      set { _leaveRoomRequest = value; }
    }
    private ProtoMsg.PutPaiRequest _putPaiRequest = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"putPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.PutPaiRequest putPaiRequest
    {
      get { return _putPaiRequest; }
      set { _putPaiRequest = value; }
    }
    private ProtoMsg.DoChiPaiRequest _doChiPaiRequest = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"doChiPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoChiPaiRequest doChiPaiRequest
    {
      get { return _doChiPaiRequest; }
      set { _doChiPaiRequest = value; }
    }
    private ProtoMsg.DoGangPaiRequest _doGangPaiRequest = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"doGangPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoGangPaiRequest doGangPaiRequest
    {
      get { return _doGangPaiRequest; }
      set { _doGangPaiRequest = value; }
    }
    private ProtoMsg.DoHuPaiRequest _doHuPaiRequest = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"doHuPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoHuPaiRequest doHuPaiRequest
    {
      get { return _doHuPaiRequest; }
      set { _doHuPaiRequest = value; }
    }
    private ProtoMsg.DoPengPaiRequest _doPengPaiRequest = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"doPengPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoPengPaiRequest doPengPaiRequest
    {
      get { return _doPengPaiRequest; }
      set { _doPengPaiRequest = value; }
    }
    private ProtoMsg.DoTingPaiRequest _doTingPaiRequest = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"doTingPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoTingPaiRequest doTingPaiRequest
    {
      get { return _doTingPaiRequest; }
      set { _doTingPaiRequest = value; }
    }
    private ProtoMsg.GuoPaiRequest _guoPaiRequest = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"guoPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GuoPaiRequest guoPaiRequest
    {
      get { return _guoPaiRequest; }
      set { _guoPaiRequest = value; }
    }
    private ProtoMsg.BuyRequest _buyRequest = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"buyRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BuyRequest buyRequest
    {
      get { return _buyRequest; }
      set { _buyRequest = value; }
    }
    private ProtoMsg.BroadCastRequest _boardcastRequest = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"boardcastRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BroadCastRequest boardcastRequest
    {
      get { return _boardcastRequest; }
      set { _boardcastRequest = value; }
    }
    private ProtoMsg.RookieRequest _rookieRequest = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"rookieRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RookieRequest rookieRequest
    {
      get { return _rookieRequest; }
      set { _rookieRequest = value; }
    }
    private ProtoMsg.IRookieRequest _irookieRequest = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"irookieRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.IRookieRequest irookieRequest
    {
      get { return _irookieRequest; }
      set { _irookieRequest = value; }
    }
    private ProtoMsg.IRookieShowRequest _irookieShowRequest = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"irookieShowRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.IRookieShowRequest irookieShowRequest
    {
      get { return _irookieShowRequest; }
      set { _irookieShowRequest = value; }
    }
    private ProtoMsg.VCodeRequest _vCodeRequest = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"vCodeRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.VCodeRequest vCodeRequest
    {
      get { return _vCodeRequest; }
      set { _vCodeRequest = value; }
    }
    private ProtoMsg.AuthRequest _authRequest = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"authRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AuthRequest authRequest
    {
      get { return _authRequest; }
      set { _authRequest = value; }
    }
    private ProtoMsg.SuggestRequest _suggestRequest = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"suggestRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.SuggestRequest suggestRequest
    {
      get { return _suggestRequest; }
      set { _suggestRequest = value; }
    }
    private ProtoMsg.LoginOutRequest _loginOutRequest = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"loginOutRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginOutRequest loginOutRequest
    {
      get { return _loginOutRequest; }
      set { _loginOutRequest = value; }
    }
    private ProtoMsg.LoginHeartRequest _loginHeartRequest = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"loginHeartRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginHeartRequest loginHeartRequest
    {
      get { return _loginHeartRequest; }
      set { _loginHeartRequest = value; }
    }
    private ProtoMsg.DoQiangTingPaiRequest _doQiangTingPaiRequest = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"doQiangTingPaiRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoQiangTingPaiRequest doQiangTingPaiRequest
    {
      get { return _doQiangTingPaiRequest; }
      set { _doQiangTingPaiRequest = value; }
    }
    private ProtoMsg.ReadyGameRequest _readyGameRequest = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"readyGameRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ReadyGameRequest readyGameRequest
    {
      get { return _readyGameRequest; }
      set { _readyGameRequest = value; }
    }
    private ProtoMsg.DissRoomRequest _dissRoomRequest = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"dissRoomRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DissRoomRequest dissRoomRequest
    {
      get { return _dissRoomRequest; }
      set { _dissRoomRequest = value; }
    }
    private ProtoMsg.ChatRequest _chatRequest = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"chatRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ChatRequest chatRequest
    {
      get { return _chatRequest; }
      set { _chatRequest = value; }
    }
    private ProtoMsg.LoginWXRequest _loginWXRequest = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"loginWXRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginWXRequest loginWXRequest
    {
      get { return _loginWXRequest; }
      set { _loginWXRequest = value; }
    }
    private ProtoMsg.ClientLogRequest _clientLogRequest = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"clientLogRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ClientLogRequest clientLogRequest
    {
      get { return _clientLogRequest; }
      set { _clientLogRequest = value; }
    }
    private ProtoMsg.LuckyRequest _luckyRequest = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"luckyRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LuckyRequest luckyRequest
    {
      get { return _luckyRequest; }
      set { _luckyRequest = value; }
    }
    private ProtoMsg.WelfareRequest _welfareRequest = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"welfareRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.WelfareRequest welfareRequest
    {
      get { return _welfareRequest; }
      set { _welfareRequest = value; }
    }
    private ProtoMsg.RankRequest _rankRequest = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"rankRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RankRequest rankRequest
    {
      get { return _rankRequest; }
      set { _rankRequest = value; }
    }
    private ProtoMsg.RankAwardRequest _rankAwardRequest = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"rankAwardRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RankAwardRequest rankAwardRequest
    {
      get { return _rankAwardRequest; }
      set { _rankAwardRequest = value; }
    }
    private ProtoMsg.DelegateRequest _delegateRequest = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"delegateRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DelegateRequest delegateRequest
    {
      get { return _delegateRequest; }
      set { _delegateRequest = value; }
    }
    private ProtoMsg.ShareRequest _shareRequest = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"shareRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ShareRequest shareRequest
    {
      get { return _shareRequest; }
      set { _shareRequest = value; }
    }
    private ProtoMsg.MailRequest _mailRequest = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"mailRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.MailRequest mailRequest
    {
      get { return _mailRequest; }
      set { _mailRequest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private ProtoMsg.DoTingPaiResponse _doTingPaiResponse = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"doTingPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoTingPaiResponse doTingPaiResponse
    {
      get { return _doTingPaiResponse; }
      set { _doTingPaiResponse = value; }
    }
    private ProtoMsg.RegisterResponse _registerResponse = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"registerResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RegisterResponse registerResponse
    {
      get { return _registerResponse; }
      set { _registerResponse = value; }
    }
    private ProtoMsg.LoginResponse _loginResponse = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginResponse loginResponse
    {
      get { return _loginResponse; }
      set { _loginResponse = value; }
    }
    private ProtoMsg.CreateRoomResponse _createRoomResponse = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.CreateRoomResponse createRoomResponse
    {
      get { return _createRoomResponse; }
      set { _createRoomResponse = value; }
    }
    private ProtoMsg.JoinRoomResponse _joinRoomResponse = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"joinRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.JoinRoomResponse joinRoomResponse
    {
      get { return _joinRoomResponse; }
      set { _joinRoomResponse = value; }
    }
    private ProtoMsg.LeaveRoomResponse _leaveRoomResponse = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"leaveRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LeaveRoomResponse leaveRoomResponse
    {
      get { return _leaveRoomResponse; }
      set { _leaveRoomResponse = value; }
    }
    private ProtoMsg.PutPaiResponse _putPaiResponse = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"putPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.PutPaiResponse putPaiResponse
    {
      get { return _putPaiResponse; }
      set { _putPaiResponse = value; }
    }
    private ProtoMsg.DoChiPaiResponse _doChiPaiResponse = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"doChiPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoChiPaiResponse doChiPaiResponse
    {
      get { return _doChiPaiResponse; }
      set { _doChiPaiResponse = value; }
    }
    private ProtoMsg.DoGangPaiResponse _doGangPaiResponse = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"doGangPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoGangPaiResponse doGangPaiResponse
    {
      get { return _doGangPaiResponse; }
      set { _doGangPaiResponse = value; }
    }
    private ProtoMsg.DoHuPaiResponse _doHuPaiResponse = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"doHuPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoHuPaiResponse doHuPaiResponse
    {
      get { return _doHuPaiResponse; }
      set { _doHuPaiResponse = value; }
    }
    private ProtoMsg.DoPengPaiResponse _doPengPaiResponse = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"doPengPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoPengPaiResponse doPengPaiResponse
    {
      get { return _doPengPaiResponse; }
      set { _doPengPaiResponse = value; }
    }
    private ProtoMsg.GuoPaiResponse _guoPaiResponse = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"guoPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GuoPaiResponse guoPaiResponse
    {
      get { return _guoPaiResponse; }
      set { _guoPaiResponse = value; }
    }
    private ProtoMsg.BuyResponse _buyResponse = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"buyResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BuyResponse buyResponse
    {
      get { return _buyResponse; }
      set { _buyResponse = value; }
    }
    private ProtoMsg.BroadCastResponse _boardcastResponse = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"boardcastResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BroadCastResponse boardcastResponse
    {
      get { return _boardcastResponse; }
      set { _boardcastResponse = value; }
    }
    private ProtoMsg.RookieResponse _rookieResponse = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"rookieResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RookieResponse rookieResponse
    {
      get { return _rookieResponse; }
      set { _rookieResponse = value; }
    }
    private ProtoMsg.IRookieResponse _irookieResponse = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"irookieResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.IRookieResponse irookieResponse
    {
      get { return _irookieResponse; }
      set { _irookieResponse = value; }
    }
    private ProtoMsg.IRookieShowResponse _irookieShowResponse = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"irookieShowResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.IRookieShowResponse irookieShowResponse
    {
      get { return _irookieShowResponse; }
      set { _irookieShowResponse = value; }
    }
    private ProtoMsg.VCodeResponse _vCodeResponse = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"vCodeResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.VCodeResponse vCodeResponse
    {
      get { return _vCodeResponse; }
      set { _vCodeResponse = value; }
    }
    private ProtoMsg.AuthResponse _authResponse = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"authResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AuthResponse authResponse
    {
      get { return _authResponse; }
      set { _authResponse = value; }
    }
    private ProtoMsg.SuggestResponse _suggestResponse = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"suggestResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.SuggestResponse suggestResponse
    {
      get { return _suggestResponse; }
      set { _suggestResponse = value; }
    }
    private ProtoMsg.LoginOutResponse _loginOutResponse = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"loginOutResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginOutResponse loginOutResponse
    {
      get { return _loginOutResponse; }
      set { _loginOutResponse = value; }
    }
    private ProtoMsg.DoQiangTingPaiResponse _doQiangTingPaiResponse = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"doQiangTingPaiResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoQiangTingPaiResponse doQiangTingPaiResponse
    {
      get { return _doQiangTingPaiResponse; }
      set { _doQiangTingPaiResponse = value; }
    }
    private ProtoMsg.ReadyGameResponse _readyGameResponse = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"readyGameResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ReadyGameResponse readyGameResponse
    {
      get { return _readyGameResponse; }
      set { _readyGameResponse = value; }
    }
    private ProtoMsg.DissRoomResponse _dissRoomResponse = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"dissRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DissRoomResponse dissRoomResponse
    {
      get { return _dissRoomResponse; }
      set { _dissRoomResponse = value; }
    }
    private ProtoMsg.ChatResponse _chatResponse = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"chatResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ChatResponse chatResponse
    {
      get { return _chatResponse; }
      set { _chatResponse = value; }
    }
    private ProtoMsg.LuckyResponse _luckyResponse = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"luckyResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LuckyResponse luckyResponse
    {
      get { return _luckyResponse; }
      set { _luckyResponse = value; }
    }
    private ProtoMsg.WelfareResponse _welfareResponse = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"welfareResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.WelfareResponse welfareResponse
    {
      get { return _welfareResponse; }
      set { _welfareResponse = value; }
    }
    private ProtoMsg.RankResponse _rankResponse = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"rankResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RankResponse rankResponse
    {
      get { return _rankResponse; }
      set { _rankResponse = value; }
    }
    private ProtoMsg.RankAwardResponse _rankAwardResponse = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"rankAwardResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.RankAwardResponse rankAwardResponse
    {
      get { return _rankAwardResponse; }
      set { _rankAwardResponse = value; }
    }
    private ProtoMsg.DelegateResponse _delegateResponse = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"delegateResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DelegateResponse delegateResponse
    {
      get { return _delegateResponse; }
      set { _delegateResponse = value; }
    }
    private ProtoMsg.LoginHeartResponse _loginHeartResponse = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"loginHeartResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LoginHeartResponse loginHeartResponse
    {
      get { return _loginHeartResponse; }
      set { _loginHeartResponse = value; }
    }
    private ProtoMsg.ShareResponse _shareResponse = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"shareResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ShareResponse shareResponse
    {
      get { return _shareResponse; }
      set { _shareResponse = value; }
    }
    private ProtoMsg.MailResponse _mailResponse = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"mailResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.MailResponse mailResponse
    {
      get { return _mailResponse; }
      set { _mailResponse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Notify")]
  public partial class Notify : global::ProtoBuf.IExtensible
  {
    public Notify() {}
    
    private ProtoMsg.JoinRoomNotify _joinRoomNotify = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"joinRoomNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.JoinRoomNotify joinRoomNotify
    {
      get { return _joinRoomNotify; }
      set { _joinRoomNotify = value; }
    }
    private ProtoMsg.LeaveRoomNotify _leaveRoomNotify = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leaveRoomNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.LeaveRoomNotify leaveRoomNotify
    {
      get { return _leaveRoomNotify; }
      set { _leaveRoomNotify = value; }
    }
    private ProtoMsg.StartGameNotify _startGameNotify = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startGameNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.StartGameNotify startGameNotify
    {
      get { return _startGameNotify; }
      set { _startGameNotify = value; }
    }
    private ProtoMsg.InitPaiNotify _initPaiNotify = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"initPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.InitPaiNotify initPaiNotify
    {
      get { return _initPaiNotify; }
      set { _initPaiNotify = value; }
    }
    private ProtoMsg.GetPaiNotify _getPaiNotify = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"getPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GetPaiNotify getPaiNotify
    {
      get { return _getPaiNotify; }
      set { _getPaiNotify = value; }
    }
    private ProtoMsg.PutPaiNotify _putPaiNotify = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"putPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.PutPaiNotify putPaiNotify
    {
      get { return _putPaiNotify; }
      set { _putPaiNotify = value; }
    }
    private ProtoMsg.CanPaiNotify _canPaiNotify = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"canPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.CanPaiNotify canPaiNotify
    {
      get { return _canPaiNotify; }
      set { _canPaiNotify = value; }
    }
    private ProtoMsg.DoChiPaiNotify _doChiPaiNotify = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"doChiPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoChiPaiNotify doChiPaiNotify
    {
      get { return _doChiPaiNotify; }
      set { _doChiPaiNotify = value; }
    }
    private ProtoMsg.DoGangPaiNotify _doGangPaiNotify = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"doGangPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoGangPaiNotify doGangPaiNotify
    {
      get { return _doGangPaiNotify; }
      set { _doGangPaiNotify = value; }
    }
    private ProtoMsg.DoHuPaiNotify _doHuPaiNotify = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"doHuPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoHuPaiNotify doHuPaiNotify
    {
      get { return _doHuPaiNotify; }
      set { _doHuPaiNotify = value; }
    }
    private ProtoMsg.DoPengPaiNotify _doPengPaiNotify = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"doPengPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoPengPaiNotify doPengPaiNotify
    {
      get { return _doPengPaiNotify; }
      set { _doPengPaiNotify = value; }
    }
    private ProtoMsg.DoTingPaiNotify _doTingPaiNotify = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"doTingPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoTingPaiNotify doTingPaiNotify
    {
      get { return _doTingPaiNotify; }
      set { _doTingPaiNotify = value; }
    }
    private ProtoMsg.GuoPaiNotify _guoPaiNotify = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"guoPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GuoPaiNotify guoPaiNotify
    {
      get { return _guoPaiNotify; }
      set { _guoPaiNotify = value; }
    }
    private ProtoMsg.DoPutPaiNotify _doPutPaiNotify = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"doPutPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoPutPaiNotify doPutPaiNotify
    {
      get { return _doPutPaiNotify; }
      set { _doPutPaiNotify = value; }
    }
    private ProtoMsg.BaoPaiShowNotify _baopaiShowNotify = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"baopaiShowNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BaoPaiShowNotify baopaiShowNotify
    {
      get { return _baopaiShowNotify; }
      set { _baopaiShowNotify = value; }
    }
    private ProtoMsg.BaoPaiChangeNotify _baopaiChangeNotify = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"baopaiChangeNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.BaoPaiChangeNotify baopaiChangeNotify
    {
      get { return _baopaiChangeNotify; }
      set { _baopaiChangeNotify = value; }
    }
    private ProtoMsg.GameTimeTickNotify _gameTimeTickNotify = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"gameTimeTickNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GameTimeTickNotify gameTimeTickNotify
    {
      get { return _gameTimeTickNotify; }
      set { _gameTimeTickNotify = value; }
    }
    private ProtoMsg.DoQiangTingPaiNotify _doQiangTingPaiNotify = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"doQiangTingPaiNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DoQiangTingPaiNotify doQiangTingPaiNotify
    {
      get { return _doQiangTingPaiNotify; }
      set { _doQiangTingPaiNotify = value; }
    }
    private ProtoMsg.ReadyGameNotify _readyGameNotify = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"readyGameNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ReadyGameNotify readyGameNotify
    {
      get { return _readyGameNotify; }
      set { _readyGameNotify = value; }
    }
    private ProtoMsg.ConnectNotify _connectNotify = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"connectNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ConnectNotify connectNotify
    {
      get { return _connectNotify; }
      set { _connectNotify = value; }
    }
    private ProtoMsg.DisConnectNotify _disConnectNotify = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"disConnectNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DisConnectNotify disConnectNotify
    {
      get { return _disConnectNotify; }
      set { _disConnectNotify = value; }
    }
    private ProtoMsg.DissRoomNotify _dissRoomNotify = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"dissRoomNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DissRoomNotify dissRoomNotify
    {
      get { return _dissRoomNotify; }
      set { _dissRoomNotify = value; }
    }
    private ProtoMsg.ChatNotify _chatNotify = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"chatNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ChatNotify chatNotify
    {
      get { return _chatNotify; }
      set { _chatNotify = value; }
    }
    private ProtoMsg.GameEndNotify _gameEndNotify = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"gameEndNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GameEndNotify gameEndNotify
    {
      get { return _gameEndNotify; }
      set { _gameEndNotify = value; }
    }
    private ProtoMsg.AssetUpdate _assetUpdateNotify = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"assetUpdateNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AssetUpdate assetUpdateNotify
    {
      get { return _assetUpdateNotify; }
      set { _assetUpdateNotify = value; }
    }
    private ProtoMsg.DelegateNotify _delegateNotify = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"delegateNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.DelegateNotify delegateNotify
    {
      get { return _delegateNotify; }
      set { _delegateNotify = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg")]
  public partial class Msg : global::ProtoBuf.IExtensible
  {
    public Msg() {}
    
    private ProtoMsg.EnumMsg _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoMsg.EnumMsg type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ProtoMsg.Request _request = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Request request
    {
      get { return _request; }
      set { _request = value; }
    }
    private ProtoMsg.Response _response = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Response response
    {
      get { return _response; }
      set { _response = value; }
    }
    private ProtoMsg.Notify _notify = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"notify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Notify notify
    {
      get { return _notify; }
      set { _notify = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnumMsg")]
    public enum EnumMsg
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"registerrequest", Value=1)]
      registerrequest = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"registerresponse", Value=2)]
      registerresponse = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginrequest", Value=3)]
      loginrequest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginresponse", Value=4)]
      loginresponse = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"createroomrequest", Value=5)]
      createroomrequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"createroomresponse", Value=6)]
      createroomresponse = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"joinroomrequest", Value=7)]
      joinroomrequest = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"joinroomresponse", Value=8)]
      joinroomresponse = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"joinroomnotify", Value=9)]
      joinroomnotify = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"leaveroomrequest", Value=10)]
      leaveroomrequest = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"leaveroomresponse", Value=11)]
      leaveroomresponse = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"leaveroomnotify", Value=12)]
      leaveroomnotify = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"startgamenotify", Value=13)]
      startgamenotify = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"initpainotify", Value=14)]
      initpainotify = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"getpainotify", Value=17)]
      getpainotify = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"putpairequest", Value=18)]
      putpairequest = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"putpairesponse", Value=19)]
      putpairesponse = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"putpainotify", Value=20)]
      putpainotify = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"canpainotify", Value=21)]
      canpainotify = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dochipairequest", Value=22)]
      dochipairequest = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dochipairesponse", Value=23)]
      dochipairesponse = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dochipainotify", Value=24)]
      dochipainotify = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dogangpairequest", Value=25)]
      dogangpairequest = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dogangpairesponse", Value=26)]
      dogangpairesponse = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dogangpainotify", Value=27)]
      dogangpainotify = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dohupairequest", Value=28)]
      dohupairequest = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dohupairesponse", Value=29)]
      dohupairesponse = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dohupainotify", Value=30)]
      dohupainotify = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dopengpairequest", Value=31)]
      dopengpairequest = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dopengpairesponse", Value=32)]
      dopengpairesponse = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dopengpainotify", Value=33)]
      dopengpainotify = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dotingpairequest", Value=34)]
      dotingpairequest = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dotingpairesponse", Value=35)]
      dotingpairesponse = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dotingpainotify", Value=36)]
      dotingpainotify = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"gameendnotify", Value=37)]
      gameendnotify = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guopairequest", Value=38)]
      guopairequest = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guopairesponse", Value=39)]
      guopairesponse = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guopainotify", Value=40)]
      guopainotify = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"gamehuangnotify", Value=41)]
      gamehuangnotify = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"doputpainotify", Value=42)]
      doputpainotify = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"buyrequest", Value=43)]
      buyrequest = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"buyresponse", Value=44)]
      buyresponse = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"boardcastrequest", Value=45)]
      boardcastrequest = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"boardcastresponse", Value=46)]
      boardcastresponse = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"baopaishownotify", Value=47)]
      baopaishownotify = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"baopaichangenotify", Value=48)]
      baopaichangenotify = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rookierequest", Value=49)]
      rookierequest = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rookieresponse", Value=50)]
      rookieresponse = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"irookierequest", Value=51)]
      irookierequest = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"irookieresponse", Value=52)]
      irookieresponse = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"irookieshowrequest", Value=53)]
      irookieshowrequest = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"irookieshowresponse", Value=54)]
      irookieshowresponse = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"gametimeticknotify", Value=55)]
      gametimeticknotify = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"vcoderequest", Value=56)]
      vcoderequest = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"vcoderesponse", Value=57)]
      vcoderesponse = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"authrequest", Value=58)]
      authrequest = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"authresponse", Value=59)]
      authresponse = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"suggestrequest", Value=60)]
      suggestrequest = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"suggestresponse", Value=61)]
      suggestresponse = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginoutrequest", Value=62)]
      loginoutrequest = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginoutresponse", Value=63)]
      loginoutresponse = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginheartrequest", Value=64)]
      loginheartrequest = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"doqiangtingpairequest", Value=65)]
      doqiangtingpairequest = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"doqiangtingpairesponse", Value=66)]
      doqiangtingpairesponse = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"doqiangtingpainotify", Value=67)]
      doqiangtingpainotify = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"applepayrequest", Value=68)]
      applepayrequest = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"applepayresponse", Value=69)]
      applepayresponse = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"readygamerequest", Value=70)]
      readygamerequest = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"readygameresponse", Value=71)]
      readygameresponse = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"readygamenotify", Value=72)]
      readygamenotify = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"connectnotify", Value=73)]
      connectnotify = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"disconnectnotify", Value=74)]
      disconnectnotify = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dissroomrequest", Value=75)]
      dissroomrequest = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dissroomresponse", Value=76)]
      dissroomresponse = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dissroomgamenotify", Value=77)]
      dissroomgamenotify = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"gameovernotify", Value=78)]
      gameovernotify = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"chatrequest", Value=79)]
      chatrequest = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"chatresponse", Value=80)]
      chatresponse = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"chatnotify", Value=81)]
      chatnotify = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginwxrequest", Value=82)]
      loginwxrequest = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"clientlogrequest", Value=83)]
      clientlogrequest = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"luckyrequest", Value=84)]
      luckyrequest = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"luckyresponse", Value=85)]
      luckyresponse = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"assetupdatenotify", Value=86)]
      assetupdatenotify = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"welfarerequest", Value=87)]
      welfarerequest = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"welfareresponse", Value=88)]
      welfareresponse = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rankrequest", Value=89)]
      rankrequest = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rankresponse", Value=90)]
      rankresponse = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rankawardrequest", Value=91)]
      rankawardrequest = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rankawardresponse", Value=92)]
      rankawardresponse = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"delegaterequest", Value=93)]
      delegaterequest = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"delegateresponse", Value=94)]
      delegateresponse = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"delegatenotify", Value=95)]
      delegatenotify = 95,
            
      [global::ProtoBuf.ProtoEnum(Name=@"loginheartresponse", Value=96)]
      loginheartresponse = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"sharerequest", Value=97)]
      sharerequest = 97,
            
      [global::ProtoBuf.ProtoEnum(Name=@"shareresponse", Value=98)]
      shareresponse = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"mailrequest", Value=99)]
      mailrequest = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"mailresponse", Value=100)]
      mailresponse = 100
    }
  
}