//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pai")]
  public partial class Pai : global::ProtoBuf.IExtensible
  {
    public Pai() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue
    {
      get { return _nValue; }
      set { _nValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiPai")]
  public partial class ChiPai : global::ProtoBuf.IExtensible
  {
    public ChiPai() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nValue1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nValue1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue1
    {
      get { return _nValue1; }
      set { _nValue1 = value; }
    }
    private int _nValue2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nValue2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue2
    {
      get { return _nValue2; }
      set { _nValue2 = value; }
    }
    private int _nValue3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nValue3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue3
    {
      get { return _nValue3; }
      set { _nValue3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PengPai")]
  public partial class PengPai : global::ProtoBuf.IExtensible
  {
    public PengPai() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue
    {
      get { return _nValue; }
      set { _nValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GangPai")]
  public partial class GangPai : global::ProtoBuf.IExtensible
  {
    public GangPai() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private int _nValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nValue
    {
      get { return _nValue; }
      set { _nValue = value; }
    }
    private int _nGangState;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nGangState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nGangState
    {
      get { return _nGangState; }
      set { _nGangState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderPai")]
  public partial class OrderPai : global::ProtoBuf.IExtensible
  {
    public OrderPai() {}
    
    private ProtoMsg.Pai _pai = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private ProtoMsg.ChiPai _chipai = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chipai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.ChiPai chipai
    {
      get { return _chipai; }
      set { _chipai = value; }
    }
    private ProtoMsg.PengPai _pengpai = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pengpai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.PengPai pengpai
    {
      get { return _pengpai; }
      set { _pengpai = value; }
    }
    private ProtoMsg.GangPai _gangpai = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gangpai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.GangPai gangpai
    {
      get { return _gangpai; }
      set { _gangpai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PaiPool")]
  public partial class PaiPool : global::ProtoBuf.IExtensible
  {
    public PaiPool() {}
    
    private int _nType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nType
    {
      get { return _nType; }
      set { _nType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _nValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"nValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> nValue
    {
      get { return _nValue; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanHuPai")]
  public partial class CanHuPai : global::ProtoBuf.IExtensible
  {
    public CanHuPai() {}
    
    private ProtoMsg.Pai _pai;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanHuPaiPool")]
  public partial class CanHuPaiPool : global::ProtoBuf.IExtensible
  {
    public CanHuPaiPool() {}
    
    private ProtoMsg.Pai _pai;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai pai
    {
      get { return _pai; }
      set { _pai = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.CanHuPai> _pool = new global::System.Collections.Generic.List<ProtoMsg.CanHuPai>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.CanHuPai> pool
    {
      get { return _pool; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GamerPaiPool")]
  public partial class GamerPaiPool : global::ProtoBuf.IExtensible
  {
    public GamerPaiPool() {}
    
    private int _nID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nID
    {
      get { return _nID; }
      set { _nID = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _pool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> pool
    {
      get { return _pool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _chiPool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(3, Name=@"chiPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> chiPool
    {
      get { return _chiPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _pengPool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(4, Name=@"pengPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> pengPool
    {
      get { return _pengPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _mGangPool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(5, Name=@"mGangPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> mGangPool
    {
      get { return _mGangPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _aGangPool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(6, Name=@"aGangPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> aGangPool
    {
      get { return _aGangPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.PaiPool> _putPool = new global::System.Collections.Generic.List<ProtoMsg.PaiPool>();
    [global::ProtoBuf.ProtoMember(7, Name=@"putPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.PaiPool> putPool
    {
      get { return _putPool; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoMsg.OrderPai> _orderPai = new global::System.Collections.Generic.List<ProtoMsg.OrderPai>();
    [global::ProtoBuf.ProtoMember(8, Name=@"orderPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.OrderPai> orderPai
    {
      get { return _orderPai; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}