//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: put_pai.proto
// Note: requires additional types generated from: pai.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PutPaiRequest")]
  public partial class PutPaiRequest : global::ProtoBuf.IExtensible
  {
    public PutPaiRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sRoomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sRoomID
    {
      get { return _sRoomID; }
      set { _sRoomID = value; }
    }
    private ProtoMsg.Pai _putPai;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"putPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai putPai
    {
      get { return _putPai; }
      set { _putPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PutPaiResponse")]
  public partial class PutPaiResponse : global::ProtoBuf.IExtensible
  {
    public PutPaiResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.Pai _putPai = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"putPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.Pai putPai
    {
      get { return _putPai; }
      set { _putPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PutPaiNotify")]
  public partial class PutPaiNotify : global::ProtoBuf.IExtensible
  {
    public PutPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private ProtoMsg.Pai _putPai;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"putPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.Pai putPai
    {
      get { return _putPai; }
      set { _putPai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoPutPaiNotify")]
  public partial class DoPutPaiNotify : global::ProtoBuf.IExtensible
  {
    public DoPutPaiNotify() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private int _nPutState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nPutState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nPutState
    {
      get { return _nPutState; }
      set { _nPutState = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.CanHuPaiPool> _huPais = new global::System.Collections.Generic.List<ProtoMsg.CanHuPaiPool>();
    [global::ProtoBuf.ProtoMember(3, Name=@"huPais", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.CanHuPaiPool> huPais
    {
      get { return _huPais; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}