//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: rank.proto
// Note: requires additional types generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankRecord")]
  public partial class RankRecord : global::ProtoBuf.IExtensible
  {
    public RankRecord() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private int _nWinCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nWinCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nWinCount
    {
      get { return _nWinCount; }
      set { _nWinCount = value; }
    }
    private int _nScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nScore
    {
      get { return _nScore; }
      set { _nScore = value; }
    }
    private string _sName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sName
    {
      get { return _sName; }
      set { _sName = value; }
    }
    private string _sHeadimg = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sHeadimg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sHeadimg
    {
      get { return _sHeadimg; }
      set { _sHeadimg = value; }
    }
    private int _nRank = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nRank
    {
      get { return _nRank; }
      set { _nRank = value; }
    }
    private int _nRankAward = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"nRankAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nRankAward
    {
      get { return _nRankAward; }
      set { _nRankAward = value; }
    }
    private int _nRankAwardType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"nRankAwardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nRankAwardType
    {
      get { return _nRankAwardType; }
      set { _nRankAwardType = value; }
    }
    private bool _bCanAward = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bCanAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bCanAward
    {
      get { return _bCanAward; }
      set { _bCanAward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankRecordAll")]
  public partial class RankRecordAll : global::ProtoBuf.IExtensible
  {
    public RankRecordAll() {}
    
    private ProtoMsg.RankRecord _rankRequster;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rankRequster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.RankRecord rankRequster
    {
      get { return _rankRequster; }
      set { _rankRequster = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.RankRecord> _rankRecords = new global::System.Collections.Generic.List<ProtoMsg.RankRecord>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rankRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.RankRecord> rankRecords
    {
      get { return _rankRecords; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankRequest")]
  public partial class RankRequest : global::ProtoBuf.IExtensible
  {
    public RankRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankResponse")]
  public partial class RankResponse : global::ProtoBuf.IExtensible
  {
    public RankResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.RankRecordAll _rankDayRecords;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rankDayRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.RankRecordAll rankDayRecords
    {
      get { return _rankDayRecords; }
      set { _rankDayRecords = value; }
    }
    private ProtoMsg.RankRecordAll _rankWeekRecords;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rankWeekRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.RankRecordAll rankWeekRecords
    {
      get { return _rankWeekRecords; }
      set { _rankWeekRecords = value; }
    }
    private ProtoMsg.RankRecordAll _rankMonthRecords;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rankMonthRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.RankRecordAll rankMonthRecords
    {
      get { return _rankMonthRecords; }
      set { _rankMonthRecords = value; }
    }
    private ProtoMsg.RankRecordAll _rankYearRecords;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rankYearRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.RankRecordAll rankYearRecords
    {
      get { return _rankYearRecords; }
      set { _rankYearRecords = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankAwardRequest")]
  public partial class RankAwardRequest : global::ProtoBuf.IExtensible
  {
    public RankAwardRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private int _nRankType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nRankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nRankType
    {
      get { return _nRankType; }
      set { _nRankType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankAwardResponse")]
  public partial class RankAwardResponse : global::ProtoBuf.IExtensible
  {
    public RankAwardResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}