//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: register.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterRequest")]
  public partial class RegisterRequest : global::ProtoBuf.IExtensible
  {
    public RegisterRequest() {}
    
    private string _sName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sName
    {
      get { return _sName; }
      set { _sName = value; }
    }
    private string _sPassWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sPassWord
    {
      get { return _sPassWord; }
      set { _sPassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterResponse")]
  public partial class RegisterResponse : global::ProtoBuf.IExtensible
  {
    public RegisterResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private int _nUserID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}