//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: rookie.proto
// Note: requires additional types generated from: assets.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RookieRecord")]
  public partial class RookieRecord : global::ProtoBuf.IExtensible
  {
    public RookieRecord() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _nUserNick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nUserNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nUserNick
    {
      get { return _nUserNick; }
      set { _nUserNick = value; }
    }
    private int _nInviteTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nInviteTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nInviteTime
    {
      get { return _nInviteTime; }
      set { _nInviteTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RookieRequest")]
  public partial class RookieRequest : global::ProtoBuf.IExtensible
  {
    public RookieRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sICode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sICode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sICode
    {
      get { return _sICode; }
      set { _sICode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RookieResponse")]
  public partial class RookieResponse : global::ProtoBuf.IExtensible
  {
    public RookieResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IRookieRequest")]
  public partial class IRookieRequest : global::ProtoBuf.IExtensible
  {
    public IRookieRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private int _nAwards;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nAwards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nAwards
    {
      get { return _nAwards; }
      set { _nAwards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IRookieResponse")]
  public partial class IRookieResponse : global::ProtoBuf.IExtensible
  {
    public IRookieResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private ProtoMsg.AssetUpdate _newAssets;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoMsg.AssetUpdate newAssets
    {
      get { return _newAssets; }
      set { _newAssets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IRookieShowRequest")]
  public partial class IRookieShowRequest : global::ProtoBuf.IExtensible
  {
    public IRookieShowRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IRookieShowResponse")]
  public partial class IRookieShowResponse : global::ProtoBuf.IExtensible
  {
    public IRookieShowResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private int _nAwardCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nAwardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nAwardCount
    {
      get { return _nAwardCount; }
      set { _nAwardCount = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMsg.RookieRecord> _records = new global::System.Collections.Generic.List<ProtoMsg.RookieRecord>();
    [global::ProtoBuf.ProtoMember(3, Name=@"records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoMsg.RookieRecord> records
    {
      get { return _records; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}