//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: suggest.proto
namespace ProtoMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestRequest")]
  public partial class SuggestRequest : global::ProtoBuf.IExtensible
  {
    public SuggestRequest() {}
    
    private int _nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nUserID
    {
      get { return _nUserID; }
      set { _nUserID = value; }
    }
    private string _sPhone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sPhone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sPhone
    {
      get { return _sPhone; }
      set { _sPhone = value; }
    }
    private string _sSuggest;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sSuggest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sSuggest
    {
      get { return _sSuggest; }
      set { _sSuggest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestResponse")]
  public partial class SuggestResponse : global::ProtoBuf.IExtensible
  {
    public SuggestResponse() {}
    
    private int _nErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nErrorCode
    {
      get { return _nErrorCode; }
      set { _nErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}